services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.12
    # build:
    # context: ..
    # dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/telegram-news-reader?authSource=admin
    depends_on:
      - mongodb
    networks:
      - telegram-news-network
    command: sleep infinity

  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=telegram-news-reader
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - telegram-news-network

volumes:
  mongodb_dev_data:


networks:
  telegram-news-network:
    driver: bridge
